#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
/etc/vlc/start.sh &
/usr/bin/kiwix-serve --daemon --port=8099 --library /home/chip/content/kiwix/ibrary.xml
exit 0
